In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

## Loading Datasets

In [25]:
df=pd.read_csv("D:\eway bills 2021-22\StudentsPerformance.csv")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

## Exploring Data

In [4]:
print(df.head(3))

   gender race/ethnicity parental level of education     lunch  \
0  female        group B           bachelor's degree  standard
1  female        group C                some college  standard
2  female        group B             master's degree  standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93

In [12]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
None

In [13]:
print(df.shape)

(1000, 8)

In [14]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [15]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [16]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [17]:
df.index

RangeIndex(start=0, stop=1000, step=1)

## Selecting and Filtering

In [18]:
df['math score'] #single column

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

In [19]:
df[['reading score','writing score']]

     reading score  writing score
0               72             74
1               90             88
2               95             93
3               57             44
4               78             75
..             ...            ...
995             99             95
996             55             55
997             71             65
998             78             77
999             86             86

[1000 rows x 2 columns]

In [22]:
df.loc[1:5]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78

In [14]:
df[df['reading score']>90]  # filtering single based on conditions

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
2,female,group B,master's degree,standard,none,90,95,93
6,female,group B,some college,standard,completed,88,95,92
102,female,group D,associate's degree,standard,none,85,91,89
106,female,group D,master's degree,standard,none,87,100,100
114,female,group E,bachelor's degree,standard,completed,99,100,100
...,...,...,...,...,...,...,...,...
957,female,group D,master's degree,standard,none,92,100,100
962,female,group E,associate's degree,standard,none,100,100,100
970,female,group D,bachelor's degree,standard,none,89,100,100
979,female,group C,associate's degree,standard,none,91,95,94
995,female,group E,master's degree,standard,completed,88,99,95

In [5]:
df[df['gender'] == 'female'] # finding total number of females

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
...,...,...,...,...,...,...,...,...
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [6]:
df[df['gender']=='male']

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
10,male,group C,associate's degree,standard,none,58,54,52
...,...,...,...,...,...,...,...,...
985,male,group A,high school,standard,none,57,51,54
987,male,group E,some high school,standard,completed,81,75,76
990,male,group E,high school,free/reduced,completed,86,81,75
994,male,group A,high school,standard,none,63,63,62
996,male,group C,high school,free/reduced,none,62,55,55

In [23]:
df[(df['math score']>60)&(df['reading score']>98)]  ## filtering on multiple conditions

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
106,female,group D,master's degree,standard,none,87,100,100
114,female,group E,bachelor's degree,standard,completed,99,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,93
165,female,group C,bachelor's degree,standard,completed,96,100,100
179,female,group D,some high school,standard,completed,97,100,100
381,male,group C,associate's degree,standard,completed,87,100,95
403,female,group D,high school,standard,completed,88,99,100
458,female,group E,bachelor's degree,standard,none,100,100,100
546,female,group A,some high school,standard,completed,92,100,97
566,female,group E,bachelor's degree,free/reduced,completed,92,100,100
594,female,group C,bachelor's degree,standard,completed,92,100,99
685,female,group E,master's degree,standard,completed,94,99,100
712,female,group D,some college,standard,none,98,100,99
886,female,group E,associate's degree,standard,completed,93,100,95
903,female,group D,bachelor's degree,free/reduced,completed,93,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
957,female,group D,master's degree,standard,none,92,100,100
962,female,group E,associate's degree,standard,none,100,100,100
970,female,group D,bachelor's degree,standard,none,89,100,100
995,female,group E,master's degree,standard,completed,88,99,95

In [24]:
df[(df['race/ethnicity'].str.contains('group E'))] ## filetring based on string conditions

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
32,female,group E,master's degree,free/reduced,none,56,72,65
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
44,female,group E,associate's degree,free/reduced,none,50,56,54
50,male,group E,some college,standard,none,53,55,48
...,...,...,...,...,...,...,...,...
962,female,group E,associate's degree,standard,none,100,100,100
968,female,group E,associate's degree,standard,none,68,76,67
987,male,group E,some high school,standard,completed,81,75,76
990,male,group E,high school,free/reduced,completed,86,81,75
995,female,group E,master's degree,standard,completed,88,99,95

In [26]:
df[(df['test preparation course']=='completed')]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1,female,group C,some college,standard,completed,69,90,88
6,female,group B,some college,standard,completed,88,95,92
8,male,group D,high school,free/reduced,completed,64,64,67
13,male,group A,some college,standard,completed,78,72,70
18,male,group C,master's degree,free/reduced,completed,46,42,46
...,...,...,...,...,...,...,...,...
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77

In [31]:
df[(df['gender'].notnull())] ## dispalying only not null rows

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [33]:
df[(df['gender'].isnull())] ## display the values with null rows
## since there is no null values it is empty

Empty DataFrame
Columns: [gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score]
Index: []

In [40]:

df[~(df['math score']<88)] ## displaying the row whose writing score is not less 88

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
2,female,group B,master's degree,standard,none,90,95,93
6,female,group B,some college,standard,completed,88,95,92
16,male,group C,high school,standard,none,88,89,86
34,male,group E,some college,standard,none,97,87,82
53,male,group D,high school,standard,none,88,78,75
...,...,...,...,...,...,...,...,...
957,female,group D,master's degree,standard,none,92,100,100
962,female,group E,associate's degree,standard,none,100,100,100
970,female,group D,bachelor's degree,standard,none,89,100,100
979,female,group C,associate's degree,standard,none,91,95,94
995,female,group E,master's degree,standard,completed,88,99,95

In [43]:
df[(df['lunch'].isin(['standard']))]  ## filetring rows whether luch matches in standard

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
...,...,...,...,...,...,...,...,...
987,male,group E,some high school,standard,completed,81,75,76
991,female,group B,some high school,standard,completed,65,82,78
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
998,female,group D,some college,standard,completed,68,78,77

## Modifying Data

In [74]:
df['new_column']=df['writing score']+[10]
df['new_column'] #create
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_column
0,female,group B,bachelor's degree,standard,none,72,72,74,84
1,female,group C,some college,standard,completed,69,90,88,98
2,female,group B,master's degree,standard,none,90,95,93,103
3,male,group A,associate's degree,free/reduced,none,47,57,44,54
4,male,group C,some college,standard,none,76,78,75,85
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,105
996,male,group C,high school,free/reduced,none,62,55,55,65
997,female,group C,high school,free/reduced,completed,59,71,65,75
998,female,group D,some college,standard,completed,68,78,77,87
999,female,group D,some college,free/reduced,none,77,86,86,96

In [85]:
df.rename(columns={'new_column':'evaluation'},inplace=True)  ## rename the column
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,evaluation,total
0,female,group B,bachelor's degree,standard,none,72,72,74,84.0,218.0
1,female,group C,some college,standard,completed,69,90,88,98.0,247.0
2,female,group B,master's degree,standard,none,90,95,93,103.0,278.0
3,male,group A,bachelor's degree,free/reduced,none,80,40,50,NaN,NaN
4,male,group C,some college,free/reduced,none,76,78,75,85.0,229.0
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,105.0,282.0
996,male,group C,high school,free/reduced,none,62,55,55,65.0,172.0
997,female,group C,high school,free/reduced,completed,59,71,65,75.0,195.0
998,female,group D,some college,standard,completed,68,78,77,87.0,223.0
999,female,group D,some college,free/reduced,none,77,86,86,96.0,249.0

In [75]:
df['total']=df['math score']+df['writing score']+df['reading score']
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_column,total
0,female,group B,bachelor's degree,standard,none,72,72,74,84,218
1,female,group C,some college,standard,completed,69,90,88,98,247
2,female,group B,master's degree,standard,none,90,95,93,103,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,54,148
4,male,group C,some college,standard,none,76,78,75,85,229
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,105,282
996,male,group C,high school,free/reduced,none,62,55,55,65,172
997,female,group C,high school,free/reduced,completed,59,71,65,75,195
998,female,group D,some college,standard,completed,68,78,77,87,223
999,female,group D,some college,free/reduced,none,77,86,86,96,249

In [76]:
df.at[4,'lunch',]='free/reduced'  # updating the data
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_column,total
0,female,group B,bachelor's degree,standard,none,72,72,74,84,218
1,female,group C,some college,standard,completed,69,90,88,98,247
2,female,group B,master's degree,standard,none,90,95,93,103,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,54,148
4,male,group C,some college,free/reduced,none,76,78,75,85,229
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,105,282
996,male,group C,high school,free/reduced,none,62,55,55,65,172
997,female,group C,high school,free/reduced,completed,59,71,65,75,195
998,female,group D,some college,standard,completed,68,78,77,87,223
999,female,group D,some college,free/reduced,none,77,86,86,96,249

In [77]:
df.loc[3] = {
    'gender': 'male',
    'race/ethnicity': 'group A',
    'parental level of education': "bachelor's degree",
    'lunch': 'free/reduced',
    'test preparation course': 'none',
    'math score': 80,
    'reading score': 40,
    'writing score': 50
}
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_column,total
0,female,group B,bachelor's degree,standard,none,72,72,74,84.0,218.0
1,female,group C,some college,standard,completed,69,90,88,98.0,247.0
2,female,group B,master's degree,standard,none,90,95,93,103.0,278.0
3,male,group A,bachelor's degree,free/reduced,none,80,40,50,NaN,NaN
4,male,group C,some college,free/reduced,none,76,78,75,85.0,229.0
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,105.0,282.0
996,male,group C,high school,free/reduced,none,62,55,55,65.0,172.0
997,female,group C,high school,free/reduced,completed,59,71,65,75.0,195.0
998,female,group D,some college,standard,completed,68,78,77,87.0,223.0
999,female,group D,some college,free/reduced,none,77,86,86,96.0,249.0

## Handling Missing Values

In [4]:
df.isnull()         # Shows True/False for nulls
#df.isnull().sum()   # Shows how many nulls in each column

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [5]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [79]:
df.dropna() #it drops the row with null values but since in this data set there is no null value rows so it remains same

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_column,total
0,female,group B,bachelor's degree,standard,none,72,72,74,84.0,218.0
1,female,group C,some college,standard,completed,69,90,88,98.0,247.0
2,female,group B,master's degree,standard,none,90,95,93,103.0,278.0
4,male,group C,some college,free/reduced,none,76,78,75,85.0,229.0
5,female,group B,associate's degree,standard,none,71,83,78,88.0,232.0
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,105.0,282.0
996,male,group C,high school,free/reduced,none,62,55,55,65.0,172.0
997,female,group C,high school,free/reduced,completed,59,71,65,75.0,195.0
998,female,group D,some college,standard,completed,68,78,77,87.0,223.0
999,female,group D,some college,free/reduced,none,77,86,86,96.0,249.0

In [9]:
df.fillna(0)  # it fills the null row with 0,but since there no null value it remains same

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [105]:
import numpy as np
data = {
    'A':[1,2,np.nan,4," ",np.nan],
    'B':[np.nan,2,3," ",np.nan,np.nan],
    'C':[1,2,3," ",4,np.nan],
    'D':[np.nan,np.nan,np.nan,np.nan,np.nan,np.nan]
}
df=pd.DataFrame(data)
df

     A    B    C   D
0    1  NaN    1 NaN
1    2    2    2 NaN
2  NaN    3    3 NaN
3    4           NaN
4       NaN    4 NaN
5  NaN  NaN  NaN NaN

In [90]:
df.isnull().sum()

A    2
B    3
C    1
D    6
dtype: int64

In [95]:
df.dropna() ## drop all the rows with null values

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [97]:
df.dropna(axis=1) ## drops all the columns which have null values present

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

In [100]:
df.dropna(how='all') # this will remove row in which all values are blank. row 5 is removed

     A    B  C   D
0    1  NaN  1 NaN
1    2    2  2 NaN
2  NaN    3  3 NaN
3    4         NaN
4       NaN  4 NaN

In [101]:
df.dropna(axis=1,how='all') #remove columns in which each value is nan. column D is removed

     A    B    C
0    1  NaN    1
1    2    2    2
2  NaN    3    3
3    4
4       NaN    4
5  NaN  NaN  NaN

In [102]:
df.dropna(subset=['B']) #remove row where B column has nan value

     A  B  C   D
1    2  2  2 NaN
2  NaN  3  3 NaN
3    4       NaN

In [108]:
import pandas as pd 
import numpy as np

data = {
    'A':[1,2,np.nan,4,5],
    'B':[np.nan,8,9,np.nan,5],
    'C':[1,7,3,9,5]
   # 'D':['A','B','C','D','E']
}

df = pd.DataFrame(data)
df

     A    B  C
0  1.0  NaN  1
1  2.0  8.0  7
2  NaN  9.0  3
3  4.0  NaN  9
4  5.0  5.0  5

In [112]:
df.replace(np.nan,4) ## all the null values is replaced by value 4

     A    B  C
0  1.0  4.0  1
1  2.0  8.0  7
2  4.0  9.0  3
3  4.0  4.0  9
4  5.0  5.0  5

In [118]:
## Forward Fill
df.ffill() ## it fills the null value with its back value

     A    B  C
0  1.0  NaN  1
1  2.0  8.0  7
2  2.0  9.0  3
3  4.0  9.0  9
4  5.0  5.0  5

In [119]:
## Backward fill
df.bfill() ## it fills its null value with forward value

     A    B  C
0  1.0  8.0  1
1  2.0  8.0  7
2  4.0  9.0  3
3  4.0  5.0  9
4  5.0  5.0  5

In [110]:
df.fillna(df.mean()) ## fills all the null values with mean

     A         B  C
0  1.0  7.333333  1
1  2.0  8.000000  7
2  3.0  9.000000  3
3  4.0  7.333333  9
4  5.0  5.000000  5

## Removing Duplicates

In [123]:
df.drop_duplicates() ## since no duplicates present in the data it remained as it is

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [146]:
import pandas as pd

data = {
    'Name':['Kishore','Sai','Shahzad','Sai','Kishore'],
    'Age':[26,23,25,23,27],
    'City':['Hyderabad','Chennai','Delhi','Chennai','Hyderabad'],
    
}
df = pd.DataFrame(data)
df

      Name  Age       City
0  Kishore   26  Hyderabad
1      Sai   23    Chennai
2  Shahzad   25      Delhi
3      Sai   23    Chennai
4  Kishore   27  Hyderabad

In [139]:
df.drop_duplicates()

      Name  Age       City
0  Kishore   26  Hyderabad
1      Sai   23    Chennai
2  Shahzad   25      Delhi
4  Kishore   27  Hyderabad

In [141]:
df.drop_duplicates(subset=['Name'])  ## removes the rows with repeated names

      Name  Age       City
0  Kishore   26  Hyderabad
1      Sai   23    Chennai
2  Shahzad   25      Delhi

In [144]:
df.drop_duplicates(subset=['Name','Age']) ## removes the rows if name and age are same

      Name  Age       City
0  Kishore   26  Hyderabad
1      Sai   23    Chennai
2  Shahzad   25      Delhi
4  Kishore   27  Hyderabad

In [147]:
df.drop_duplicates(keep= 'last')

      Name  Age       City
0  Kishore   26  Hyderabad
2  Shahzad   25      Delhi
3      Sai   23    Chennai
4  Kishore   27  Hyderabad

## Grouping and Aggregation

In [5]:
# Get value counts of lunch types by gender
df.groupby(['gender', 'lunch']).size()

gender  lunch
female  free/reduced    189
        standard        329
male    free/reduced    166
        standard        316
dtype: int64

In [5]:
data = {
    'EmployeeID':[1,2,3,4,5,6,7,8,9],
    'Name':['Shahzad','Dheeraj','Kishore','Praveen','Sandeep','Deepak','Srikant',
           'Anandh','Sai'],
    'Department':['HR','Finance','HR','Finance','IT','IT','HR','Finance','IT'],
    'Salary':[60000,75000,62000,80000,90000,85000,61000,78000,92000],
    'Experience (Years)':[3,5,2,8,4,6,2,7,5]
}

df = pd.DataFrame(data)
df

   EmployeeID     Name Department  Salary  Experience (Years)
0           1  Shahzad         HR   60000                   3
1           2  Dheeraj    Finance   75000                   5
2           3  Kishore         HR   62000                   2
3           4  Praveen    Finance   80000                   8
4           5  Sandeep         IT   90000                   4
5           6   Deepak         IT   85000                   6
6           7  Srikant         HR   61000                   2
7           8   Anandh    Finance   78000                   7
8           9      Sai         IT   92000                   5

In [11]:
df.groupby("Department")["Salary"].sum()

Department
Finance    233000
HR         183000
IT         267000
Name: Salary, dtype: int64

In [15]:
df.groupby("Department")["Salary"].agg(["max","sum","mean"]) ## grouping multiple functions at a time

              max     sum          mean
Department
Finance     80000  233000  77666.666667
HR          62000  183000  61000.000000
IT          92000  267000  89000.000000

In [22]:
df.groupby(["Department","Experience (Years)"])["Salary"].sum()

Department  Experience (Years)
Finance     5                      75000
            7                      78000
            8                      80000
HR          2                     123000
            3                      60000
IT          4                      90000
            5                      92000
            6                      85000
Name: Salary, dtype: int64

## Sorting & Reading

In [29]:
df.sort_values(by='math score',ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
451,female,group E,some college,standard,none,100,92,97
458,female,group E,bachelor's degree,standard,none,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,93
623,male,group A,some college,standard,completed,100,96,86
...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33
787,female,group B,some college,standard,none,19,38,32
17,female,group B,some high school,free/reduced,none,18,32,28
980,female,group B,high school,free/reduced,none,8,24,23
59,female,group C,some high school,free/reduced,none,0,17,10

In [31]:
df.sort_values(by=['gender','math score'],ascending=[True,True])

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10
980,female,group B,high school,free/reduced,none,8,24,23
17,female,group B,some high school,free/reduced,none,18,32,28
787,female,group B,some college,standard,none,19,38,32
145,female,group C,some college,free/reduced,none,22,39,33
...,...,...,...,...,...,...,...,...
306,male,group E,some college,standard,completed,99,87,81
149,male,group E,associate's degree,free/reduced,completed,100,100,93
623,male,group A,some college,standard,completed,100,96,86
625,male,group D,some college,standard,completed,100,97,99
916,male,group E,bachelor's degree,standard,completed,100,100,100

In [32]:
df.sort_index()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [38]:
import numpy as np

df=pd.DataFrame({'Marks':[80,np.nan,60,90,np.nan]})
df

   Marks
0   80.0
1    NaN
2   60.0
3   90.0
4    NaN

In [41]:
df.sort_values(by='Marks',na_position='last') ## Sorting positions by null values first or last

   Marks
2   60.0
0   80.0
3   90.0
1    NaN
4    NaN

## Combining Data

In [55]:
data1 = {'ID':[1,2,3,4],
        'Name':['alka','Kishore','Sai','Shamali']}
df1 = pd.DataFrame(data1)
df1

   ID     Name
0   1     alka
1   2  Kishore
2   3      Sai
3   4  Shamali

In [56]:
data2 = {
    'ID':[1,2,4,5],
    'Age':[25,30,35,28]
}
df2 = pd.DataFrame(data2)
df2

   ID  Age
0   1   25
1   2   30
2   4   35
3   5   28

In [57]:
pd.concat([df1,df2])

   ID     Name   Age
0   1     alka   NaN
1   2  Kishore   NaN
2   3      Sai   NaN
3   4  Shamali   NaN
0   1      NaN  25.0
1   2      NaN  30.0
2   4      NaN  35.0
3   5      NaN  28.0

In [58]:
pd.concat([df1,df2],ignore_index = True)

   ID     Name   Age
0   1     alka   NaN
1   2  Kishore   NaN
2   3      Sai   NaN
3   4  Shamali   NaN
4   1      NaN  25.0
5   2      NaN  30.0
6   4      NaN  35.0
7   5      NaN  28.0

In [59]:
pd.concat([df1,df2],axis = 1)

   ID     Name  ID  Age
0   1     alka   1   25
1   2  Kishore   2   30
2   3      Sai   4   35
3   4  Shamali   5   28

In [62]:
pd.merge(df1,df2,on = 'ID',how = 'inner')

   ID     Name  Age
0   1     alka   25
1   2  Kishore   30
2   4  Shamali   35

In [65]:
pd.merge(df1,df2,on='ID',how='right')

   ID     Name  Age
0   1     alka   25
1   2  Kishore   30
2   4  Shamali   35
3   5      NaN   28

## Reading and writing in excel and csv file

In [71]:
import pandas as pd

data = {
    'Name':['Sandeep','Rani','Sainath'],
    'Age':[23,31,28],
    'City':['Guntur','Hyderabad','kurnool']
}

df = pd.DataFrame(data)
# Writing DataFrame to a CSV file


df.to_csv('Output1.csv',sep=';',header = True,index=False)

In [72]:
pd.read_csv('Output1.csv')

        Name;Age;City
0   Sandeep;23;Guntur
1   Rani;31;Hyderabad
2  Sainath;28;kurnool

In [73]:
import pandas as pd

data = {
    'Name':['Sandeep','Rani','Sainath'],
    'Age':[23,31,28],
    'City':['Guntur','Hyderabad','kurnool']
}

df = pd.DataFrame(data)

# Writing DataFrame to a Excel file

df.to_excel('Output1.xlsx',sheet_name='Data Sheet',index=False)

In [74]:
# Reading the Excel file 
pd.read_excel("Output1.xlsx")

      Name  Age       City
0  Sandeep   23     Guntur
1     Rani   31  Hyderabad
2  Sainath   28    kurnool